on:
  push:
    branches:
      - main
  pull_request:

name: Build
jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Dev Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:
  release_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Release Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
