on:
  push:
    branches:
      - main
  pull_request:

name: Format
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: True
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
