on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests (libvelosiparser)
jobs:
  compile_and_test:
    name: "libvelosiparser"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: libvelosiparser_test
        uses: actions-rs/cargo@v1
        with:
          command: test
