on:
  push:
    branches:
      - main
  pull_request:

name: Unit Tests (parser)
jobs:
  compile_and_test:
    name: "parser"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: parser_test
        uses: actions-rs/cargo@v1
        with:
          command: test
